# Generated by Django 2.2 on 2019-12-07 20:39

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=200)),
                ('telefone', phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31)),
                ('bairro', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=200)),
                ('cpf_cnpj', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
