# Generated by Django 2.2 on 2020-02-05 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('qtd', models.SmallIntegerField()),
                ('valor', models.SmallIntegerField()),
                ('data_entrada', models.DateField(auto_now=True)),
                ('data_vencimento', models.DateField()),
            ],
        ),
    ]
