# Generated by Django 2.2 on 2020-02-05 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_estoque'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estoque',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
