# Generated by Django 2.2 on 2019-12-07 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20191207_1743'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('prod_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('item', models.CharField(max_length=100)),
                ('qtd', models.SmallIntegerField()),
                ('data_entrada', models.DateField()),
                ('data_vencimento', models.DateField()),
            ],
        ),
    ]
