# Generated by Django 2.2 on 2020-02-06 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_pedido'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estoque',
            options={'verbose_name': 'Estoque', 'verbose_name_plural': 'Estoque'},
        ),
    ]
