# Generated by Django 2.2 on 2019-12-07 21:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_estoque'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estoque',
            old_name='item',
            new_name='nome',
        ),
        migrations.RemoveField(
            model_name='estoque',
            name='prod_id',
        ),
        migrations.AddField(
            model_name='estoque',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='estoque',
            name='data_entrada',
            field=models.DateField(auto_now=True),
        ),
    ]
