# Generated by Django 2.2 on 2019-12-07 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20191207_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='estoque',
            name='valor',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
