# Generated by Django 2.2 on 2019-12-07 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_estoque_valor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Estoque',
        ),
    ]
