# Generated by Django 2.2 on 2019-12-08 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_estoque'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receita', models.CharField(max_length=200)),
                ('pdf_receita', models.FileField(upload_to='')),
            ],
        ),
    ]
