# Generated by Django 2.2 on 2019-12-08 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_pedido_valor_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='observacoes',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
