# Generated by Django 2.2 on 2019-12-08 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20191208_0059'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='entregue',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
