# Generated by Django 2.2 on 2019-12-08 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_pedido_entregue'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receita',
            old_name='pdf_receita',
            new_name='arquivo',
        ),
    ]
